"""Pentest Report Generator — Markdown & HTML reports with findings."""

import os
from datetime import datetime, timezone
from html import escape as _esc
from typing import List, Dict, Optional
from string import Template


class Finding:
    """Represents a single pentest finding."""
    
    SEVERITIES = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    SEVERITY_COLORS = {
        "critical": "#dc2626", "high": "#ea580c", "medium": "#d97706",
        "low": "#2563eb", "info": "#6b7280"
    }
    
    def __init__(self, title: str, severity: str = "info",
                 description: str = "", evidence: str = "",
                 remediation: str = "", tool: str = "",
                 category: str = "General", cvss: str = "",
                 cve: str = "", affected: str = ""):
        self.title = title
        self.severity = severity.lower()
        self.description = description
        self.evidence = evidence
        self.remediation = remediation
        self.tool = tool
        self.category = category
        self.cvss = cvss
        self.cve = cve
        self.affected = affected
        self.timestamp = datetime.now(timezone.utc)
    
    def to_dict(self) -> dict:
        return {
            "title": self.title, "severity": self.severity,
            "description": self.description, "evidence": self.evidence,
            "remediation": self.remediation, "tool": self.tool,
            "category": self.category, "cvss": self.cvss,
            "cve": self.cve, "affected": self.affected,
            "timestamp": self.timestamp.isoformat(),
        }


class ReportGenerator:
    """Generates professional pentest reports in Markdown and HTML."""
    
    def __init__(self):
        self.findings: List[Finding] = []
        self.target: str = ""
        self.scope: str = ""
        self.tester: str = "CVA Agent"
        self.executive_summary: str = ""
        self.methodology: str = ""
        self.start_time: datetime = datetime.now(timezone.utc)
        self.raw_evidence: List[Dict] = []
    
    def add_finding(self, finding: Finding):
        """Add a finding to the report."""
        self.findings.append(finding)
    
    def add_evidence(self, tool: str, command: str, output: str):
        """Add raw evidence/scan output to appendix."""
        self.raw_evidence.append({
            "tool": tool, "command": command,
            "output": output[:5000],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
    
    def _sorted_findings(self) -> List[Finding]:
        """Return findings sorted by severity."""
        return sorted(self.findings, key=lambda f: Finding.SEVERITIES.get(f.severity, 99))
    
    def _severity_stats(self) -> Dict[str, int]:
        """Count findings per severity."""
        stats = {s: 0 for s in Finding.SEVERITIES}
        for f in self.findings:
            stats[f.severity] = stats.get(f.severity, 0) + 1
        return stats
    
    def generate_markdown(self) -> str:
        """Generate a complete pentest report in Markdown."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        stats = self._severity_stats()
        
        md = []
        md.append(f"# Penetration Test Report")
        md.append(f"\n**Target:** {self.target}")
        md.append(f"**Scope:** {self.scope}")
        md.append(f"**Tester:** {self.tester}")
        md.append(f"**Date:** {self.start_time.strftime('%Y-%m-%d')} → {now}")
        md.append(f"**Generated by:** CVA (Cognitive VAPT Assistant)")
        
        # Executive Summary
        md.append(f"\n---\n\n## Executive Summary\n")
        if self.executive_summary:
            md.append(self.executive_summary)
        else:
            total = len(self.findings)
            md.append(f"A penetration test was conducted against **{self.target}**. "
                      f"A total of **{total}** findings were identified:")
            md.append(f"\n| Severity | Count |")
            md.append(f"|----------|-------|")
            for sev, count in stats.items():
                if count > 0:
                    md.append(f"| {sev.capitalize()} | {count} |")
        
        # Methodology
        md.append(f"\n---\n\n## Methodology\n")
        if self.methodology:
            md.append(self.methodology)
        else:
            md.append("Testing followed the standard VAPT methodology:\n")
            md.append("1. **Reconnaissance** — Passive and active information gathering")
            md.append("2. **Enumeration** — Service, port, and directory enumeration")
            md.append("3. **Vulnerability Analysis** — Identifying weaknesses")
            md.append("4. **Exploitation** — Validating vulnerabilities")
            md.append("5. **Post-Exploitation** — Assessing impact")
            md.append("6. **Reporting** — Documenting findings and remediation")
        
        # Findings
        md.append(f"\n---\n\n## Findings\n")
        for i, f in enumerate(self._sorted_findings(), 1):
            md.append(f"\n### {i}. [{f.severity.upper()}] {f.title}\n")
            md.append(f"| Field | Value |")
            md.append(f"|-------|-------|")
            md.append(f"| **Severity** | {f.severity.capitalize()} |")
            if f.cvss: md.append(f"| **CVSS** | {f.cvss} |")
            if f.cve: md.append(f"| **CVE** | {f.cve} |")
            md.append(f"| **Category** | {f.category} |")
            if f.affected: md.append(f"| **Affected** | {f.affected} |")
            if f.tool: md.append(f"| **Discovered by** | {f.tool} |")
            
            if f.description:
                md.append(f"\n**Description:**\n{f.description}")
            if f.evidence:
                md.append(f"\n**Evidence:**\n```\n{f.evidence[:1000]}\n```")
            if f.remediation:
                md.append(f"\n**Remediation:**\n{f.remediation}")
        
        # Evidence Appendix
        if self.raw_evidence:
            md.append(f"\n---\n\n## Appendix: Raw Evidence\n")
            for i, ev in enumerate(self.raw_evidence, 1):
                md.append(f"\n### A{i}. {ev['tool']} ({ev['timestamp']})\n")
                md.append(f"**Command:** `{ev['command']}`\n")
                md.append(f"```\n{ev['output'][:2000]}\n```")
        
        return "\n".join(md)
    
    def generate_html(self) -> str:
        """Generate a styled HTML pentest report."""
        md_content = self.generate_markdown()
        stats = self._severity_stats()
        
        # Build severity bar
        total = max(len(self.findings), 1)
        bar_html = ""
        for sev, count in stats.items():
            if count > 0:
                pct = (count / total) * 100
                color = Finding.SEVERITY_COLORS.get(sev, "#666")
                bar_html += f'<div style="width:{pct}%;background:{color};height:30px;display:inline-block;text-align:center;color:white;line-height:30px;font-size:12px;" title="{sev}">{count} {sev}</div>'
        
        # Build findings HTML (all finding-derived text is HTML-escaped to
        # avoid corrupting/injecting the report with tool output that contains
        # <, > or &).
        findings_html = ""
        for i, f in enumerate(self._sorted_findings(), 1):
            color = Finding.SEVERITY_COLORS.get(f.severity, "#666")
            title = _esc(f.title)
            category = _esc(f.category)
            cve = _esc(f.cve)
            cvss = _esc(f.cvss)
            affected = _esc(f.affected)
            description = _esc(f.description)
            evidence = _esc(f.evidence[:1000])
            remediation = _esc(f.remediation)
            findings_html += f'''
            <div style="border-left:4px solid {color};padding:12px 16px;margin:12px 0;background:#1a1a2e;border-radius:0 8px 8px 0;">
                <h3 style="margin:0;color:#e0e0e0;">{i}. {title}
                    <span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;margin-left:8px;">{f.severity.upper()}</span>
                </h3>
                {"<p style='color:#aaa;margin:4px 0;'><strong>CVE:</strong> " + cve + "</p>" if f.cve else ""}
                {"<p style='color:#aaa;margin:4px 0;'><strong>CVSS:</strong> " + cvss + "</p>" if f.cvss else ""}
                <p style="color:#aaa;margin:4px 0;"><strong>Category:</strong> {category}</p>
                {"<p style='color:#aaa;margin:4px 0;'><strong>Affected:</strong> " + affected + "</p>" if f.affected else ""}
                {"<p style='color:#ccc;margin:8px 0;'>" + description + "</p>" if f.description else ""}
                {"<pre style='background:#0d0d1a;padding:8px;border-radius:4px;color:#4ade80;font-size:12px;overflow-x:auto;'>" + evidence + "</pre>" if f.evidence else ""}
                {"<p style='color:#60a5fa;margin:8px 0;'><strong>Remediation:</strong> " + remediation + "</p>" if f.remediation else ""}
            </div>'''

        # Evidence appendix (also escaped)
        evidence_html = ""
        for i, ev in enumerate(self.raw_evidence, 1):
            ev_tool = _esc(str(ev.get('tool', '')))
            ev_ts = _esc(str(ev.get('timestamp', '')))
            ev_cmd = _esc(str(ev.get('command', '')))
            ev_out = _esc(str(ev.get('output', ''))[:2000])
            evidence_html += f'''
            <div style="margin:12px 0;padding:12px;background:#1a1a2e;border-radius:8px;">
                <h4 style="color:#e0e0e0;margin:0;">A{i}. {ev_tool}</h4>
                <p style="color:#aaa;font-size:12px;">{ev_ts}</p>
                <code style="color:#60a5fa;">$ {ev_cmd}</code>
                <pre style="background:#0d0d1a;padding:8px;border-radius:4px;color:#4ade80;font-size:11px;max-height:300px;overflow:auto;">{ev_out}</pre>
            </div>'''
        
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pentest Report — {_esc(self.target)}</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',system-ui,sans-serif; background:#0f0f23; color:#e0e0e0; padding:40px; line-height:1.6; }}
        .container {{ max-width:900px; margin:0 auto; }}
        .header {{ background:linear-gradient(135deg,#1e1e3f,#0f0f23); padding:40px; border-radius:16px; border:1px solid #333; margin-bottom:30px; }}
        .header h1 {{ font-size:28px; color:#60a5fa; margin-bottom:8px; }}
        .header .meta {{ color:#aaa; font-size:14px; }}
        .section {{ background:#16162b; border-radius:12px; padding:24px; margin:16px 0; border:1px solid #222; }}
        .section h2 {{ color:#60a5fa; font-size:20px; margin-bottom:12px; border-bottom:1px solid #333; padding-bottom:8px; }}
        .severity-bar {{ display:flex; border-radius:8px; overflow:hidden; margin:16px 0; }}
        table {{ width:100%; border-collapse:collapse; margin:8px 0; }}
        th, td {{ padding:8px 12px; text-align:left; border-bottom:1px solid #222; }}
        th {{ color:#60a5fa; }}
        .footer {{ text-align:center; color:#666; font-size:12px; margin-top:40px; padding:20px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ Penetration Test Report</h1>
            <div class="meta">
                <p><strong>Target:</strong> {_esc(self.target)}</p>
                <p><strong>Scope:</strong> {_esc(self.scope)}</p>
                <p><strong>Tester:</strong> {_esc(self.tester)}</p>
                <p><strong>Period:</strong> {self.start_time.strftime("%Y-%m-%d")} → {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p>
            </div>
        </div>

        <div class="section">
            <h2>📊 Summary</h2>
            <div class="severity-bar">{bar_html}</div>
            <table>
                <tr><th>Severity</th><th>Count</th></tr>
                {"".join(f"<tr><td>{s.capitalize()}</td><td>{c}</td></tr>" for s, c in stats.items() if c > 0)}
                <tr style="font-weight:bold;border-top:2px solid #444;"><td>Total</td><td>{len(self.findings)}</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>🔍 Findings</h2>
            {findings_html or "<p style='color:#666;'>No findings recorded yet.</p>"}
        </div>

        {"<div class='section'><h2>📎 Appendix: Raw Evidence</h2>" + evidence_html + "</div>" if evidence_html else ""}

        <div class="footer">
            <p>Generated by <strong>CVA</strong> (Cognitive VAPT Assistant) — {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p>
        </div>
    </div>
</body>
</html>'''
        return html
    
    def save(self, output_dir: str = "reports", fmt: str = "both", base_name: str = None) -> List[str]:
        """Save report to files. Returns list of saved paths.

        Args:
            output_dir: Directory to save reports in.
            fmt: Format — 'md', 'html', or 'both'.
            base_name: Fixed base filename (without extension). If provided,
                       the same file is overwritten on each save, enabling
                       incremental report updates within a session.
        """
        os.makedirs(output_dir, exist_ok=True)
        if base_name:
            base = base_name
        else:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            target_slug = self.target.replace(".", "_").replace("/", "_").replace(":", "_")[:30]
            base = f"pentest_{target_slug}_{timestamp}"
        
        saved = []
        
        if fmt in ("md", "both", "markdown"):
            md_path = os.path.join(output_dir, f"{base}.md")
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(self.generate_markdown())
            saved.append(md_path)

        if fmt in ("html", "both"):
            html_path = os.path.join(output_dir, f"{base}.html")
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(self.generate_html())
            saved.append(html_path)
        
        return saved
    
    def from_session(self, session_store, session_id: str):
        """Populate report from session findings and notes."""
        findings_data = session_store.get_findings(session_id)
        for fd in findings_data:
            self.add_finding(Finding(
                title=fd.get("title", fd.get("type", "Finding")),
                severity=fd.get("severity", "info"),
                description=fd.get("description", fd.get("details", "")),
                evidence=fd.get("evidence", ""),
                tool=fd.get("tool", ""),
                category=fd.get("category", fd.get("type", "General")),
                cve=fd.get("cve", ""),
                affected=fd.get("affected", fd.get("target", "")),
            ))
        
        notes = session_store.get_notes(session_id)
        for note in notes:
            self.add_evidence(
                tool=note.get("category", "manual"),
                command=f"[{note.get('category', '')}]",
                output=note.get("content", ""),
            )
